### Get
GET http://127.0.0.1:3000/album
Content-Type: application/json

### Get by id
GET http://127.0.0.1:3000/album/1
Content-Type: application/json

### Post
POST http://127.0.0.1:3000/album
Content-Type: application/json

{
    "desc": "Album xxx",
    "url": "https://fastly.picsum.photos/id/143/200/200.jpg?hmac=zGj8dhmmqaaQZDcHhU9C0itdL12zcGTpuVdQiVrYiEQ"
}
